fancybox: true
duoshuo: hsfzxjy
disqus: #disqus_shortname
google_search: true
baidu_search: #baidu_search
swiftype: #swiftype_key
tinysou: #tinysou_key
menu:
  - page: home
    directory: /
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about
  - page: rss
    directory: atom.xml
    icon: icon-rss
